# Generated by Django 3.2.4 on 2021-06-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagModel',
            new_name='PostTagModel',
        ),
        migrations.RenameField(
            model_name='authormodel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posttagmodel',
            old_name='created',
            new_name='created_at',
        ),
    ]
