# Generated by Django 3.2.4 on 2021-08-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_employeemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
