# Generated by Django 3.2.4 on 2021-08-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_employeemodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
