# Generated by Django 3.2.4 on 2021-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_employeemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee'),
        ),
    ]
