# Generated by Django 3.2.4 on 2021-09-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_faqmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveFAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'faq-question',
                'verbose_name_plural': 'faq-questions',
            },
        ),
    ]
