# Generated by Django 3.2.4 on 2021-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
