# Generated by Django 3.2.4 on 2021-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmodel_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
